# Generated by Django 4.2.6 on 2023-11-15 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0020_page_translation_accuracy"),
        ("translators", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translator",
            name="books_participated",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books_participated",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="translator",
            name="pages_translated",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translator_pages",
                to="books.page",
            ),
        ),
        migrations.AlterField(
            model_name="translator",
            name="translation_accuracy",
            field=models.PositiveIntegerField(
                blank=True, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
