# Generated by Django 4.2.6 on 2023-11-01 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Book's Name")),
                ("detail", models.TextField(verbose_name="Book's Detail")),
                ("file", models.FileField(upload_to="", verbose_name="Book's File")),
                (
                    "author",
                    models.CharField(max_length=255, verbose_name="Book's Author"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en-us", "English"), ("es-sp", "Spanish")],
                        max_length=5,
                        verbose_name="Book's Language",
                    ),
                ),
                (
                    "pages_number",
                    models.PositiveIntegerField(verbose_name="Book's Pages Number"),
                ),
                (
                    "publication_date",
                    models.DateTimeField(verbose_name="Publication Date"),
                ),
                (
                    "translated_date",
                    models.DateTimeField(blank=True, verbose_name="Translated Date"),
                ),
                (
                    "min_translators",
                    models.PositiveIntegerField(
                        verbose_name="Minimum Number of Translators to Start"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("translated", "Translated"),
                            ("in-progress", "In Progress"),
                            ("not-started", "Not Started"),
                        ],
                        max_length=11,
                        verbose_name="Book's Status",
                    ),
                ),
                (
                    "translators",
                    models.ManyToManyField(
                        related_name="book_translators",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Book's Translators",
                    ),
                ),
            ],
        ),
    ]
