# Generated by Django 4.2.6 on 2023-11-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_created_date_book_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.FileField(
                upload_to="books/original/", verbose_name="Book's File"
            ),
        ),
    ]
