# Generated by Django 4.2.6 on 2023-11-01 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0003_alter_book_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.IntegerField(verbose_name="Publication Date"),
        ),
        migrations.AlterField(
            model_name="book",
            name="translated_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Translated Date"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="translators",
            field=models.ManyToManyField(
                blank=True,
                related_name="book_translators",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Book's Translators",
            ),
        ),
    ]
