# Generated by Django 4.2.6 on 2023-11-02 09:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0004_alter_book_publication_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="waiting_timer",
            field=models.DurationField(
                default=datetime.timedelta(days=7),
                verbose_name="Waiting timer for Translators to join",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="books/pages/", verbose_name="Page's File"
                    ),
                ),
                (
                    "translated_content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Translated Content"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_pages",
                        to="books.book",
                        verbose_name="Book",
                    ),
                ),
                (
                    "translator",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="page_translator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Page's Translator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InProgressBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pages_left", models.PositiveIntegerField(verbose_name="Pages Left")),
                (
                    "extra_notes",
                    models.TextField(blank=True, null=True, verbose_name="Extra Notes"),
                ),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_progress_book",
                        to="books.book",
                        verbose_name="Book",
                    ),
                ),
            ],
        ),
    ]
