# Generated by Django 4.2.6 on 2023-11-02 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_book_waiting_timer_page_inprogressbook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="waiting_timer",
        ),
    ]
