# Generated by Django 4.2.6 on 2023-11-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0007_alter_inprogressbook_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="file",
        ),
        migrations.AddField(
            model_name="page",
            name="page",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="page",
            name="translator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="page_translator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Page's Translator",
            ),
        ),
    ]
