# Generated by Django 4.2.6 on 2023-11-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_remove_page_file_page_page_alter_page_translator"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="original_content",
            field=models.TextField(default=" ", verbose_name="Original Content"),
            preserve_default=False,
        ),
    ]
