# Generated by Django 4.2.6 on 2023-11-02 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0009_page_original_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_translated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="page",
            name="translator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="page_translator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Page's Translator",
            ),
        ),
    ]
