# Generated by Django 4.2.6 on 2023-11-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0010_page_is_translated_alter_page_translator"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
