# Generated by Django 4.2.6 on 2023-11-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0011_page_is_reviewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="inprogressbook",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
