# Generated by Django 4.2.6 on 2023-11-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0014_rename_file_book_original_file_book_translated_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="translated_file",
        ),
        migrations.AddField(
            model_name="book",
            name="translated_md_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="books/translated/markdown/",
                verbose_name="Book's Translated MD File",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="translated_pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="books/translated/pdf/",
                verbose_name="Book's Translated PDF File",
            ),
        ),
    ]
