# Generated by Django 4.2.6 on 2023-11-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0015_remove_book_translated_file_book_translated_md_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="books/cover/",
                verbose_name="Book's Cover Image",
            ),
        ),
    ]
