# Generated by Django 4.2.6 on 2023-11-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0016_book_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                upload_to="books/cover/", verbose_name="Book's Cover Image"
            ),
        ),
    ]
