# Generated by Django 4.2.6 on 2023-11-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0017_alter_book_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="translating_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Translating Date"
            ),
        ),
    ]
