# Generated by Django 4.2.6 on 2023-11-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0018_book_translating_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="translating_date",
            field=models.DateTimeField(verbose_name="Translating Date"),
        ),
    ]
