# Generated by Django 4.2.6 on 2023-11-14 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0019_alter_book_translating_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="translation_accuracy",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
                verbose_name="Translation Accuracy",
            ),
        ),
    ]
