# Generated by Django 4.2.6 on 2023-11-15 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0020_page_translation_accuracy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="translation_accuracy",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Translation Accuracy",
            ),
        ),
    ]
