# Generated by Django 4.2.6 on 2023-11-13 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_identity_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_verified",
        ),
    ]
